def_EHelper(lui) {
  rtl_li(s, ddest, id_src1->imm);
}
def_EHelper(auipc){
	rtl_addi(s,id_dest->preg,&s->pc,id_src1->imm);
}
def_EHelper(addi){
	rtl_addi(s,id_dest->preg,id_src1->preg,id_src2->imm);
}
def_EHelper(jal){
	rtl_mv(s,id_dest->preg,&s->snpc);
	rtl_j(s,id_src1->imm+s->pc);
}
def_EHelper(jalr){
	rtl_mv(s,id_dest->preg,&s->snpc);
	rtl_addi(s,t0,id_src1->preg,id_src2->imm);
	rtl_andi(s,t0,t0,0xFFFFFFFE);
	rtl_jr(s,t0);
}
def_EHelper(add){
	rtl_add(s,id_dest->preg,id_src1->preg,id_src2->preg);
}
def_EHelper(sub){
	rtl_sub(s,id_dest->preg,id_src1->preg,id_src2->preg);
}
def_EHelper(sltiu){
	rtl_setrelopi(s,RELOP_LTU,id_dest->preg,id_src1->preg,id_src2->imm);
}
def_EHelper(beq){
	rtl_jrelop(s,RELOP_EQ,id_src1->preg,id_src2->preg,s->pc+id_dest->imm);
}
def_EHelper(bne){
	rtl_jrelop(s,RELOP_NE,id_src1->preg,id_src2->preg,s->pc+id_dest->imm);
}
def_EHelper(sltu){
	rtl_setrelop(s,RELOP_LTU,id_dest->preg,id_src1->preg,id_src2->preg);
}
def_EHelper(xor){
	rtl_xor(s,id_dest->preg,id_src1->preg,id_src2->preg);
}
def_EHelper(or){
	rtl_or(s,id_dest->preg,id_src1->preg,id_src2->preg);
}
def_EHelper(srai){
	rtl_srai(s,id_dest->preg,id_src1->preg,id_src2->imm);
}
def_EHelper(sra){
	rtl_srai(s,id_dest->preg,id_src1->preg,id_src2->imm);
}
def_EHelper(blt){
	rtl_jrelop(s,RELOP_LT,id_src1->preg,id_src2->preg,s->pc+id_dest->imm);
}
def_EHelper(bge){
	rtl_jrelop(s,RELOP_GE,id_src1->preg,id_src2->preg,s->pc+id_dest->imm);
}
def_EHelper(bltu){
	rtl_jrelop(s,RELOP_LTU,id_src1->preg,id_src2->preg,s->pc+id_dest->imm);
}
def_EHelper(bgeu){
	rtl_jrelop(s,RELOP_GEU,id_src1->preg,id_src2->preg,s->pc+id_dest->imm);
}

